"""Add audit log

Revision ID: 0b313f54e980
Revises: 1629e17c7a16
Create Date: 2026-04-28 17:11:30.147968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b313f54e980'
down_revision = '1629e17c7a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('breathing_rate_intraday', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('breathing_rate_intraday_time_idx'))

    with op.batch_alter_table('daily_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('daily_summaries_date_idx'))

    with op.batch_alter_table('hrv_intraday', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('hrv_intraday_time_idx'))

    with op.batch_alter_table('intraday_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('intraday_metrics_time_idx'))

    with op.batch_alter_table('sleep_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('sleep_levels_time_idx'))

    with op.batch_alter_table('sleep_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('sleep_logs_start_time_idx'))

    with op.batch_alter_table('sleep_short_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('sleep_short_levels_time_idx'))

    with op.batch_alter_table('spo2_intraday', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('spo2_intraday_time_idx'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spo2_intraday', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('spo2_intraday_time_idx'), [sa.literal_column('time DESC')], unique=False)

    with op.batch_alter_table('sleep_short_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('sleep_short_levels_time_idx'), [sa.literal_column('time DESC')], unique=False)

    with op.batch_alter_table('sleep_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('sleep_logs_start_time_idx'), [sa.literal_column('start_time DESC')], unique=False)

    with op.batch_alter_table('sleep_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('sleep_levels_time_idx'), [sa.literal_column('time DESC')], unique=False)

    with op.batch_alter_table('intraday_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('intraday_metrics_time_idx'), [sa.literal_column('time DESC')], unique=False)

    with op.batch_alter_table('hrv_intraday', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('hrv_intraday_time_idx'), [sa.literal_column('time DESC')], unique=False)

    with op.batch_alter_table('daily_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('daily_summaries_date_idx'), [sa.literal_column('date DESC')], unique=False)

    with op.batch_alter_table('breathing_rate_intraday', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('breathing_rate_intraday_time_idx'), [sa.literal_column('time DESC')], unique=False)

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
