"""Initial schema

Revision ID: 6b2d15058568
Revises: 
Create Date: 2026-04-23 19:39:04.579444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2d15058568'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;")

    op.create_table('care_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', name='user_role'), server_default='STAFF', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_provider_id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('authorization_status', sa.Enum('INSERTED', 'AUTHORIZED', 'NON_ACTIVE', name='status_type'), server_default='INSERTED', nullable=False),
    sa.Column('device_type', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_synch', sa.DateTime(), nullable=True),
    sa.Column('daily_summaries_checkpoint', sa.Date(), nullable=True),
    sa.Column('intraday_checkpoint', sa.DateTime(), nullable=True),
    sa.Column('sleep_checkpoint', sa.Date(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['care_provider_id'], ['care_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('care_provider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['care_provider_id'], ['care_providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('daily_summaries',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('active_minutes', sa.Integer(), nullable=True),
    sa.Column('sedentary_minutes', sa.Integer(), nullable=True),
    sa.Column('nutrition_calories', sa.Float(), nullable=True),
    sa.Column('water', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('oxygen_saturation', sa.Float(), nullable=True),
    sa.Column('respiratory_rate', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'date')
    )

    op.execute("""
        SELECT create_hypertable(
            'daily_summaries',
            'date',
            chunk_time_interval => INTERVAL '1 month',
            if_not_exists => TRUE
        );
    """)

    op.create_table('intraday_metrics',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'time')
    )

    op.execute("""
        SELECT create_hypertable(
            'intraday_metrics',
            'time',
            chunk_time_interval => INTERVAL '1 month',
            if_not_exists => TRUE
        );
    """)

    op.create_table('pending_authorizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('code_verifier', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sleep_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('breathing_rate_intraday',
    sa.Column('sleep_session_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('breathing_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sleep_session_id'], ['sleep_sessions.id'], ),
    sa.PrimaryKeyConstraint('sleep_session_id', 'time')
    )

    op.execute("""
        SELECT create_hypertable(
            'breathing_rate_intraday',
            'time',
            chunk_time_interval => INTERVAL '1 month',
            if_not_exists => TRUE
        );
    """)

    op.create_table('hrv_intraday',
    sa.Column('sleep_session_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('rmssd', sa.Float(), nullable=False),
    sa.Column('lf', sa.Float(), nullable=True),
    sa.Column('hf', sa.Float(), nullable=True),
    sa.Column('coverage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sleep_session_id'], ['sleep_sessions.id'], ),
    sa.PrimaryKeyConstraint('sleep_session_id', 'time')
    )

    op.execute("""
        SELECT create_hypertable(
            'hrv_intraday',
            'time',
            chunk_time_interval => INTERVAL '1 month',
            if_not_exists => TRUE
        );
    """)

    op.create_table('sleep_levels',
    sa.Column('sleep_session_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sleep_session_id'], ['sleep_sessions.id'], ),
    sa.PrimaryKeyConstraint('sleep_session_id', 'time')
    )

    op.execute("""
        SELECT create_hypertable(
            'sleep_levels',
            'time',
            chunk_time_interval => INTERVAL '1 month',
            if_not_exists => TRUE
        );
    """)

    op.create_table('sleep_logs',
    sa.Column('sleep_session_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('is_main_sleep', sa.Boolean(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('minutes_asleep', sa.Integer(), nullable=False),
    sa.Column('minutes_awake', sa.Integer(), nullable=False),
    sa.Column('minutes_in_the_bed', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['sleep_session_id'], ['sleep_sessions.id'], ),
    sa.PrimaryKeyConstraint('sleep_session_id', 'start_time')
    )

    op.execute("""
        SELECT create_hypertable(
            'sleep_logs',
            'start_time',
            chunk_time_interval => INTERVAL '1 month',
            if_not_exists => TRUE
        );
    """)

    op.create_table('sleep_short_levels',
    sa.Column('sleep_session_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sleep_session_id'], ['sleep_sessions.id'], ),
    sa.PrimaryKeyConstraint('sleep_session_id', 'time')
    )

    op.execute("""
        SELECT create_hypertable(
            'sleep_short_levels',
            'time',
            chunk_time_interval => INTERVAL '1 month',
            if_not_exists => TRUE
        );
    """)
    op.create_table('spo2_intraday',
    sa.Column('sleep_session_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('spo2_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sleep_session_id'], ['sleep_sessions.id'], ),
    sa.PrimaryKeyConstraint('sleep_session_id', 'time')
    )

    op.execute("""
        SELECT create_hypertable(
            'spo2_intraday',
            'time',
            chunk_time_interval => INTERVAL '1 month',
            if_not_exists => TRUE
        );
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spo2_intraday')
    op.drop_table('sleep_short_levels')
    op.drop_table('sleep_logs')
    op.drop_table('sleep_levels')
    op.drop_table('hrv_intraday')
    op.drop_table('breathing_rate_intraday')
    op.drop_table('sleep_sessions')
    op.drop_table('pending_authorizations')
    op.drop_table('intraday_metrics')
    op.drop_table('daily_summaries')
    op.drop_table('staff_profiles')
    op.drop_table('devices')
    op.drop_table('users')
    op.drop_table('care_providers')

    op.execute("DROP TYPE IF EXISTS status_type CASCADE")
    op.execute("DROP TYPE IF EXISTS user_role CASCADE")
    # ### end Alembic commands ###
